---
name: OpenWisp WiFi Login Pages CI BUILD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qa-checks:
    name: QA-Checks
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Installing dependencies
        run: |
          yarn install
          pip install openwisp-utils[qa]

      - name: QA checks
        run: ./run-qa-checks

  build:
    name: Tests and Coverage
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Installing dependencies
        run: |
          yarn install
          yarn setup
      
      - name: Installing and Running OpenWISP Radius
        run: |
          git clone https://github.com/openwisp/openwisp-radius/
          cd openwisp-radius && pip install -e .
          ./tests/manage.py migrate
          ./tests/manage.py runserver &

      - name: Running Client and Server
        run: yarn start &

      - name: Tests
        run: yarn coverage

      - name: Browser Tests
        run: yarn selenium-test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
